### PR TITLE
EventFake adaptation for October

### LINKED ISSUE #5371: Event::fire() not working when testing with Event::fake()
- OctoberCMS Build: v1.1.*
- PHP Version: 7.4

### Description:
When attemoting to test an `Event::fire` in a unit test I'm recieveing the error `Error: Call to undefined method Illuminate\Support\Testing\Fakes\EventFake::fire()`. I raised this in the [Slack channel](https://octobercms.slack.com/archives/C20UWUV1C/p1606654130121500) and it was pointed out that some work would need to be carried out on the `EventFake` class. [A similar bug was recently fixed](https://github.com/octobercms/library/pull/538) for the `Mail::fake()` method.

### Steps To Reproduce:

1. Create a unit test file withing your plugin.
2. Include the test contents...

```
function testMethod() {
    Event::fake();

    Event::fire(MyCustomEvent::class);

    Event::assertDispatched(MyCustomEvent::class);
}
```

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes https://github.com/octobercms/october/issues/5371

Usage until this Event Facade is used on october/october:
```
\October\Rain\Support\Facades\Event::fake();
\Event::fire('my.test.event');
\Event::assertDispatched('my.test.event');
```

### CODE REVIEW

File: src/Support/Testing/Fakes/EventFake.php [hunk 1]
```diff
@@ -0,0 +1,15 @@
+<?php
+
+namespace October\Rain\Support\Testing\Fakes;
```
Comment (LukeTowers) [inline src/Support/Testing/Fakes/EventFake.php]:
```suggestion
<?php namespace October\Rain\Support\Testing\Fakes;
```

**Comment by mjauvin** [comment]
Were you able to test this @jonathandey ?

**Review by bennothommo — APPROVED** [review]

**Comment by bennothommo** [comment]
Looks fine to me, as long as it's tested.

@mjauvin Would you be able to create a simple test case that tests this? Doesn't have to be too intricate, just make sure that the `fire` method is called in `EventFake` when using the mock. You could use Mockery to spy on the `fire` method.

**Comment by jonathandey** [comment]
@mjauvin - Yes, I just tested it and it appears to be working as expected. Thanks for your time on this.

**Comment by mjauvin** [comment]
@bennothommo It's been tested as working by two parties, Jonathan Dey and myself. I also added a testcase as you requested.

Thanks.

**Comment by bennothommo** [comment]
Nice one, @mjauvin!
